version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: 'wednesday'
      time: '04:00'
    open-pull-requests-limit: 10
    target-branch: dev
