version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=llm_portal
    ports:
      - "6532:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
